---
# Apt section
- file: path="/etc/apt/sources.list.d/zabbix.list" state=absent
  when: ansible_os_family == "Debian"
  tags: [ "zabbix-agent", "monitoring" ]
- file: path="/etc/apt/sources.list.d/dotdeb.list" state=absent
  when: ansible_os_family == "Debian" and ansible_lsb.major_release >= 7
  tags: [ "zabbix-agent", "monitoring" ]
- apt_key: url="http://repo.zabbix.com/zabbix-official-repo.key" state=present
  when: ansible_os_family == "Debian" and ansible_lsb.major_release >= 7
  tags: [ "zabbix-agent", "monitoring" ]
- apt_repository: repo="deb http://mirrors.thzhost.com/debian-zabbix/ {{ hostvars[inventory_hostname]['ansible_lsb']['codename'] }} main" state=present
  when: ansible_os_family == "Debian" and ansible_lsb.major_release >= 7
  tags: [ "zabbix-agent", "monitoring" ]
# dotdeb for zabbix only for squeeze
- apt_key: url="http://www.dotdeb.org/dotdeb.gpg" state=present
  when: ansible_os_family == "Debian" and ansible_lsb.major_release < 7
  tags: [ "zabbix-agent", "monitoring" ]
- apt_repository: repo="deb http://packages.dotdeb.org {{ hostvars[inventory_hostname]['ansible_lsb']['codename'] }} all" state=present
  when: ansible_os_family == "Debian" and ansible_lsb.major_release < 7
  tags: [ "zabbix-agent", "monitoring" ]
# Luckily, they use the same packages name
- apt: pkg="{{ item }}" state=latest
  with_items :
    - zabbix-agent
  when: ansible_os_family == "Debian"
  tags: [ "zabbix-agent", "monitoring" ]
  
- yum: name={{item}} state=absent
  with_items :
    - zabbix20-agent
    - zabbix20-sender
    - zabbix20
    - zabbix22-agent
    - zabbix22-sender
  when: ansible_os_family == "RedHat"
  tags: [ "zabbix-agent", "monitoring" ]

- yum: name={{item}} state=latest
  with_items :
    - zabbix-agent
    - zabbix-sender
  when: ansible_os_family == "RedHat"
  tags: [ "zabbix-agent", "monitoring" ]

# Common ground
#- file: path="/etc/zabbix/zabbix_agentd.conf.d" state=absent
#- file: path="/etc/zabbix/zabbix_agentd.d" state=directory
- file: path="/etc/zabbix/scripts" state=directory
- file: path="/etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf" state=absent

- lineinfile: dest="/etc/zabbix/zabbix_agentd.conf" state=present line="Include=/etc/zabbix/zabbix_agentd.d/"
  notify: restart zabbix-agent
  tags: [ "zabbix-agent", "monitoring" ]

- synchronize: src="zabbix/scripts/" dest="/etc/zabbix/scripts/"
  notify: restart zabbix-agent
  tags: [ "zabbix-agent", "monitoring" ]

- synchronize: src="zabbix/zabbix_agentd.d/" dest="/etc/zabbix/zabbix_agentd.d/"
  notify: restart zabbix-agent
  tags: [ "zabbix-agent", "monitoring" ]

- lineinfile: dest="/etc/sudoers" line='zabbix ALL=(ALL) NOPASSWD'':'' ALL' state=present
  tags: [ "zabbix-agent", "monitoring" ]

- lineinfile: dest="/etc/sudoers" line="Defaults    requiretty" regexp="Defaults.*requiretty"  state=absent
  tags: [ "zabbix-agent", "monitoring" ]

#self-generate config
- template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items :
    - { src: zabbix/hostname.conf.j2, dest: /etc/zabbix/zabbix_agentd.d/hostname.conf }
    - { src: zabbix/server.conf.j2, dest: /etc/zabbix/zabbix_agentd.d/server.conf }
  notify: restart zabbix-agent
  tags: [ "zabbix-agent", "monitoring" ]

- service: name="zabbix-agent" enabled=yes state="started"
  tags: [ "zabbix-agent", "monitoring" ]
