---
# Apt section
- file: path="/etc/apt/sources.list.d/zabbix.list" state=absent
  when: ansible_lsb.id == "Debian"
- file: path="/etc/apt/sources.list.d/dotdeb.list" state=absent
  when: ansible_lsb.id == "Debian" and ansible_lsb.major_release >= 7
- apt_key: url="http://repo.zabbix.com/zabbix-official-repo.key" state=present
  when: ansible_lsb.id == "Debian" and ansible_lsb.major_release >= 7
- apt_repository: repo="deb http://repo.zabbix.com/zabbix/2.2/debian/ {{ hostvars[inventory_hostname]['ansible_lsb']['codename'] }} main" state=present
  when: ansible_lsb.id == "Debian" and ansible_lsb.major_release >= 7
# dotdeb for zabbix only for squeeze
- apt_key: url="http://www.dotdeb.org/dotdeb.gpg" state=present
  when: ansible_lsb.id == "Debian" and ansible_lsb.major_release < 7
- apt_repository: repo="deb http://packages.dotdeb.org {{ hostvars[inventory_hostname]['ansible_lsb']['codename'] }} all" state=present
  when: ansible_lsb.id == "Debian" and ansible_lsb.major_release < 7
# Luckily, they use the same packages name
- apt: pkg="{{ item }}" state=latest
  with_items :
    - zabbix-agent
  when: ansible_lsb.id == "Debian"
# RPM section *5 *6
- yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 6
- yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/5/x86_64/zabbix-release-2.2-1.el5.noarch.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 5
- yum: name={{item}} state=absent
  with_items :
    - zabbix20-agent
    - zabbix20-sender
    - zabbix20
    - zabbix22-agent
    - zabbix22-sender
  when: ansible_os_family == "RedHat"
- yum: name={{item}} state=latest
  with_items :
    - zabbix-agent
    - zabbix-sender
  when: ansible_os_family == "RedHat"

# Common ground
- file: path="/etc/zabbix/zabbix_agentd.conf.d" state=absent
- file: path="/etc/zabbix/zabbix_agentd.d" state=directory
- file: path="/etc/zabbix/scripts" state=directory
- file: path="/etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf" state=absent
- lineinfile: dest="/etc/zabbix/zabbix_agentd.conf" regexp="^Include=/etc/zabbix/zabbix_agentd.d/" state=present line="Include=/etc/zabbix/zabbix_agentd.d/"
  notify: restart zabbix-agent
- synchronize: src="zabbix/scripts/" dest="/etc/zabbix/scripts/"
#self-generate config
- template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items :
    - { src: zabbix/hostname.conf.j2, dest: /etc/zabbix/zabbix_agentd.d/hostname.conf }
    - { src: zabbix/server.conf.j2, dest: /etc/zabbix/zabbix_agentd.d/server.conf }
  notify: restart zabbix-agent
# service
#- service: name="zabbix-agent" state="restarted"
#  when: zabbix_config.changed
- service: name="zabbix-agent" enabled=yes state="started"
